#!/usr/bin/with-contenv bash
set +e

echo "[voltronic] Starting Voltronic JS service..."

while true; do
  node /opt/voltronic/voltronic.js
  echo "[voltronic] voltronic.js exited, restarting in 5s..."
  sleep 5
done
